_wandb:
    value:
        cli_version: 0.23.1
        e:
            lhabf69yg4mc7dv01231svxblcl4srna:
                args:
                    - --model
                    - navigator
                codePath: src\main_brain.py
                codePathLocal: main_brain.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "268434403328"
                        used: "168466452480"
                email: acidmc69@gmail.com
                executable: D:\RLMC\venv\Scripts\python.exe
                git:
                    commit: f7f61121abffa1e7e2ab24b77b5c50f1ac4fc69f
                    remote: https://github.com/AcidTheTwo/MinecraftHybridRL.git
                gpu: NVIDIA GeForce RTX 4050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 2560
                      memoryTotal: "6439305216"
                      name: NVIDIA GeForce RTX 4050 Laptop GPU
                      uuid: GPU-b4444b37-7e75-1d59-b9c7-58edc1c6fbd1
                host: LAPTOP-I19HFFDE
                memory:
                    total: "25439199232"
                os: Windows-11-10.0.26100-SP0
                program: d:\RLMC\src\main_brain.py
                python: CPython 3.13.5
                root: d:\RLMC\src
                startedAt: "2025-12-10T19:58:31.785344Z"
                writerId: lhabf69yg4mc7dv01231svxblcl4srna
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.13.5
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
architecture:
    value: DQN
batch_size:
    value: 32
gamma:
    value: 0.9
learning_rate:
    value: 1e-05
task:
    value: navigator
